sudo: required
language: minimal
services:
- docker
install:
- sudo apt-get install -y apache2-utils
script:
- htpasswd -c -i -b cadvisor/auth.htpasswd prometheus $CADVISOR_PASSWORD
- docker build -t dev.savvydatainsights.co.uk/savvy/cadvisor cadvisor
after_success:
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD dev.savvydatainsights.co.uk
- docker push dev.savvydatainsights.co.uk/savvy/cadvisor
notifications:
  slack:
    secure: LRvftYwGZ+YumqIxAeJppAnJSgqZMldL3Lvd5FngZz+E0E6zWOeMJMm6eFB9x7NUfa8jVeG4y8+iJfYFUF9gzEqmYfbT5dIaZ9X7rsjIOWoRiI7v2aIfx6gpgLCZgH+6fmRXr8DIbjSRDtpJh9j14FuNFHX9g78uf4QlVItX4CUPH1Q4Djz1zLgv3Tg8YDaYGwB10ZQwb9NURh/TToXpLPtD3uk8b+C+6KcUxYDM/sYqf6Ok2ofRNz8lVw2TVaiRSEx7Vm1mwJE7ePPUxpidxGOU8qD6yM/nEdG4q4sFuEA+gHr7B0V2JK4FlWJDnvgWoi0TM3lZY9FPpLb7OfveAP6qiByMPFNnFWlrOOKEAlxaB83ywpzT2Bq6ZCWR8wWVyy/K5ZMBAXdF7NI0quulBVGbHTbVFWBfTjoe6uR/TR0UxxMYNRMTVLmXpZ0Hy8Fy2vazdpzeVtiiPHsTHr59L1SfHBSi/vWY8JMuO3icB4LcMSzQGTR0A6C9FIKui0FgONXIPoD/hckPGbGaA+kcXsJQVB40+sfhQMbVfNVR2zSvbq3T2Kzrb0oN2ZhrYE0W03BTG6hyY8eFipEcEXLHRhYMwRzevmiAGGSEUrwnAgcbsmyzPYeJWZ1u94uocpendj49Flf0EZdjJR4AlbHqJNMm5fuIwOu/U8MkAwEq2o8=
